### PR TITLE
makefile, db scaffolding, db interface

### PR DESCRIPTION
**Pull request by NathanEpstein**

### CODE REVIEW

**Comment by NathanEpstein** [comment]
What's included:

- A Makefile for the initial setup and rebuilding. 

- Some thoroughly incomplete schema files (which you can update and run `make rebuild`).

- A JS interface to the scholars table (that code can definitely get reused to query/update other tables). The interface basically assumes you're passing an HTTP request (as expressed in the `scholars.js` route) but you could easily retool it to take a smaller object with just the params. 

- The `scholars.js` endpoint mentioned above. Whether you retool the db interface (`scholarsDbInterface.js`) depends on how much of the logic you're handling client side.

**Comment by lindslev** [comment]
excellent start 🍏

**Comment by NathanEpstein** [comment]
So am I good to merge this (I don't know what kinda system you wanna use re: PR approval)?

I'll probably also throw a testing scaffold on there but that will probably be a separate PR.

**Review by lindslev — APPROVED** [review]
ill approve dis way from nao on but ye you good to go

**Pull request merged**
